### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eliah-w** [vanita5/TwittnukerPushServer2#3]
* [ ] Migrate to ES6/ESnext
* [ ] Receive Consumer Key/Secret and Access Token/Secret from device
* [ ] Web frontend for managing registered devices and setup instructions
* [ ] Documentation/Tutorial
* [ ] Push Notifications as a service (not selfhosted) ?
    * [ ] Register and Payment process
